const wordImages = {
  // Kata kerja
  ambil: "https://i.ibb.co/xFDdTgC/Ambil.jpg",
  angkat: "https://i.ibb.co/CKyDRtL/Angkat.jpg",
  baca: "https://i.ibb.co/WfqmLPZ/Baca.jpg",
  bercakap: "https://i.ibb.co/K9BL7Xm/Bercakap.jpg",
  bawa: "https://i.ibb.co/CHscC4p/Bawa.jpg",
  beritahu: "https://i.ibb.co/wy13Lg4/Beritahu.jpg",
  berlari: "https://i.ibb.co/p4Y28D3/Berlari.jpg",
  bina: "https://i.ibb.co/mXcWwCN/Bina.jpg",
  bincang: "https://i.ibb.co/KWzygWy/Bincang.jpg",
  bohong: "https://i.ibb.co/2Pnfm2x/Bohong.jpg",
  cari: "https://i.ibb.co/sCs539m/Cari.jpg",
  dapat: "https://i.ibb.co/frJhvCZ/Dapat.jpg",
  curi: "https://i.ibb.co/y0s9VcZ/Curi.jpg",
  gaduh: "https://i.ibb.co/D8jpHzd/Gaduh.jpg",
  hantar: "https://i.ibb.co/zSGdVZ1/Hantar.jpg",
  hilang: "https://i.ibb.co/RhLpzbk/Hilang.jpg",
  ikut: "https://i.ibb.co/CvpSzMX/Ikut.jpg",
  jawab: "https://i.ibb.co/948pGWv/Jawab.jpg",
  jemput: "https://i.ibb.co/WDbsz0v/Jemput.jpg",
  kira: "https://i.ibb.co/8mZtG4r/Kira.jpg",
  jumpa: "https://i.ibb.co/S0g8D75/Jumpa.jpg",
  koyak: "https://i.ibb.co/s9zPC4Q/Koyak.jpg",
  langgar: "https://i.ibb.co/Gx20srh/Langgar.jpg",
  lihat: "https://i.ibb.co/2S0LmmK/Lihat.jpg",
  makan: "https://i.ibb.co/pd6WB8L/Makan.jpg",
  mandi: "https://i.ibb.co/RT8bLtZ/Mandi.jpg",
  menyanyi: "https://i.ibb.co/Z6ScJCq/Menyanyi.jpg",
  padam: "https://i.ibb.co/dW1gH8N/Padam.jpg",
  panggil: "https://i.ibb.co/28G8D2G/Panggil.jpg",
  pilih: "https://i.ibb.co/x3F0Ltv/Pilih.jpg",
  pinjam: "https://i.ibb.co/cvfh18d/Pinjam.jpg",
  rehat: "https://i.ibb.co/Z2brDNQ/Rehat.jpg",
  sebut: "https://i.ibb.co/86fbdkk/Sebut.jpg",
  simpan: "https://i.ibb.co/q9wmwmt/Simpan.jpg",
  tangkap: "https://i.ibb.co/DVg5fLD/Tangkap.jpg",
  tembak: "https://i.ibb.co/N72rk1W/Tembak.jpg",
  tempah: "https://i.ibb.co/FxrCw9R/Tempah.jpg",
  tidur: "https://i.ibb.co/Fq5Rwjf/Tidur.jpg",
  tinggal: "https://i.ibb.co/h21WTxs/Tinggal.jpg",
  tulis: "https://i.ibb.co/T2GWpqT/Tulis.jpg",
  tunggu: "https://i.ibb.co/9WnkLr3/Tunggu.jpg",

  // Sifat
  adil: "https://i.ibb.co/hVNdKzS/Adil.jpg",
  bagus: "https://i.ibb.co/hBh3wpn/Bagus.jpg",
  baik: "https://i.ibb.co/JK1Ldq6/Baik.jpg",
  besar: "https://i.ibb.co/FhF6LZD/Besar.jpg",
  kecil: "https://i.ibb.co/m9R8hNk/Kecil.jpg",
  cantik: "https://i.ibb.co/7SvN2Lf/Cantik.jpg",
  cepat: "https://i.ibb.co/QfG7V5f/Cepat.jpg",
  lambat: "https://i.ibb.co/p2t8XkH/Lambat.jpg",
  baru: "https://i.ibb.co/xyz/Baru.jpg",
  lama: "https://i.ibb.co/xyz/Lama.jpg",

  // Warna
  merah: "https://i.ibb.co/kc5R2dQ/Merah.jpg",
  biru: "https://i.ibb.co/fnJ7Z4X/Biru.jpg",
  hijau: "https://i.ibb.co/L8Xk3Z0/Hijau.jpg",
  kuning: "https://i.ibb.co/D9xR3V1/Kuning.jpg",
  hitam: "https://i.ibb.co/7kF3V9G/Hitam.jpg",
  putih: "https://i.ibb.co/pwD9YQ4/Putih.jpg",

  // Nombor
  satu: "https://i.ibb.co/1x3N2k5/Satu.jpg",
  dua: "https://i.ibb.co/2y4L5m6/Dua.jpg",
  tiga: "https://i.ibb.co/3z5N6n7/Tiga.jpg",
  empat: "https://i.ibb.co/4a7B8p9/Empat.jpg",
  lima: "https://i.ibb.co/5c9D1q2/Lima.jpg",
  enam: "https://i.ibb.co/6d1E2r3/Enam.jpg",
  tujuh: "https://i.ibb.co/7f2F3s4/Tujuh.jpg",
  lapan: "https://i.ibb.co/8g3H4t5/Lapan.jpg",
  sembilan: "https://i.ibb.co/9h4I5u6/Sembilan.jpg",
  sepuluh: "https://i.ibb.co/0i5J6v7/Sepuluh.jpg",

  // Tempat
  rumah: "https://i.ibb.co/abc/Home.jpg",
  sekolah: "https://i.ibb.co/abc/School.jpg",
  pejabat: "https://i.ibb.co/abc/Office.jpg",
  masjid: "https://i.ibb.co/abc/Mosque.jpg",
  pasar: "https://i.ibb.co/abc/Market.jpg",

  // Perasaan & lain-lain
  gembira: "https://i.ibb.co/abc/Happy.jpg",
  sedih: "https://i.ibb.co/abc/Sad.jpg",
  marah: "https://i.ibb.co/abc/Angry.jpg",
  takut: "https://i.ibb.co/abc/Scared.jpg",
  terkejut: "https://i.ibb.co/abc/Surprised.jpg",
  bosan: "https://i.ibb.co/abc/Bored.jpg",
  penat: "https://i.ibb.co/abc/Tired.jpg",
  sakit: "https://i.ibb.co/abc/Sick.jpg",
  lapar: "https://i.ibb.co/abc/Hungry.jpg",
  dahaga: "https://i.ibb.co/abc/Thirsty.jpg"
  const wordImages_part2 = {
  // Kata kerja tambahan
  serang: "https://i.ibb.co/abc/Serang.jpg",
  selamat: "https://i.ibb.co/abc/Selamat.jpg",
  sembunyi: "https://i.ibb.co/abc/Sembunyi.jpg",
  sediakan: "https://i.ibb.co/abc/Sediakan.jpg",
  sentuh: "https://i.ibb.co/abc/Sentuh.jpg",
  simpan: "https://i.ibb.co/abc/Simpan2.jpg",
  susun: "https://i.ibb.co/abc/Susun.jpg",
  tarik: "https://i.ibb.co/abc/Tarik.jpg",
  tolong: "https://i.ibb.co/abc/Tolong.jpg",
  tunjuk: "https://i.ibb.co/abc/Tunjuk.jpg",
  tulis: "https://i.ibb.co/abc/Tulis2.jpg",
  ubah: "https://i.ibb.co/abc/Ubah.jpg",
  undur: "https://i.ibb.co/abc/Undur.jpg",
  usap: "https://i.ibb.co/abc/Usap.jpg",
  tekan: "https://i.ibb.co/abc/Tekan.jpg",
  tekan2: "https://i.ibb.co/abc/Tekan2.jpg",
  terbang: "https://i.ibb.co/abc/Terbang.jpg",
  terapung: "https://i.ibb.co/abc/Terapung.jpg",
  tutup: "https://i.ibb.co/abc/Tutup.jpg",
  tuang: "https://i.ibb.co/abc/Tuang.jpg",
  tunjukkan: "https://i.ibb.co/abc/Tunjukkan.jpg",

  // Sifat tambahan
  keras: "https://i.ibb.co/abc/Keras.jpg",
  lembut: "https://i.ibb.co/abc/Lembut.jpg",
  panjang: "https://i.ibb.co/abc/Panjang.jpg",
  pendek: "https://i.ibb.co/abc/Pendek.jpg",
  ringan: "https://i.ibb.co/abc/Ringan.jpg",
  berat: "https://i.ibb.co/abc/Berat.jpg",
  sejuk: "https://i.ibb.co/abc/Sejuk.jpg",
  panas: "https://i.ibb.co/abc/Panas.jpg",
  baru: "https://i.ibb.co/abc/Baru2.jpg",
  lama: "https://i.ibb.co/abc/Lama2.jpg",

  // Warna tambahan
  jingga: "https://i.ibb.co/abc/Jingga.jpg",
  ungu: "https://i.ibb.co/abc/Ungu.jpg",
  kelabu: "https://i.ibb.co/abc/Kelabu.jpg",
  coklat: "https://i.ibb.co/abc/Coklat.jpg",
  pink: "https://i.ibb.co/abc/Pink.jpg",
  biru_muda: "https://i.ibb.co/abc/Biru-Muda.jpg",
  hijau_muda: "https://i.ibb.co/abc/Hijau-Muda.jpg",
  kuning_muda: "https://i.ibb.co/abc/Kuning-Muda.jpg",

  // Nombor tambahan
  sebelas: "https://i.ibb.co/abc/Sebelas.jpg",
  dua_belas: "https://i.ibb.co/abc/Dua-Belas.jpg",
  tiga_belas: "https://i.ibb.co/abc/Tiga-Belas.jpg",
  empat_belas: "https://i.ibb.co/abc/Empat-Belas.jpg",
  lima_belas: "https://i.ibb.co/abc/Lima-Belas.jpg",
  enam_belas: "https://i.ibb.co/abc/Enam-Belas.jpg",
  tujuh_belas: "https://i.ibb.co/abc/Tujuh-Belas.jpg",
  lapan_belas: "https://i.ibb.co/abc/Lapan-Belas.jpg",
  sembilan_belas: "https://i.ibb.co/abc/Sembilan-Belas.jpg",
  dua_puluh: "https://i.ibb.co/abc/Dua-Puluh.jpg",

  // Tempat tambahan
  klinik: "https://i.ibb.co/abc/Klinik.jpg",
  hospital: "https://i.ibb.co/abc/Hospital.jpg",
  taman: "https://i.ibb.co/abc/Taman.jpg",
  pantai: "https://i.ibb.co/abc/Pantai.jpg",
  padang: "https://i.ibb.co/abc/Padang.jpg",
  stesen_bas: "https://i.ibb.co/abc/Stesen-Bas.jpg",
  stesen_kereta_api: "https://i.ibb.co/abc/Stesen-Kereta-Api.jpg",
  perpustakaan: "https://i.ibb.co/abc/Perpustakaan.jpg",
  pasaraya: "https://i.ibb.co/abc/Pasaraya.jpg",
  kafe: "https://i.ibb.co/abc/Kafe.jpg",

  // Perasaan tambahan
  seronok: "https://i.ibb.co/abc/Seronok.jpg",
  gementar: "https://i.ibb.co/abc/Gementar.jpg",
  kesal: "https://i.ibb.co/abc/Kesal.jpg",
  kecewa: "https://i.ibb.co/abc/Kecewa.jpg",
  lega: "https://i.ibb.co/abc/Lega.jpg",
  rindu: "https://i.ibb.co/abc/Rindu.jpg",
  malu: "https://i.ibb.co/abc/Malu.jpg",
  cemas: "https://i.ibb.co/abc/Cemas.jpg",
  puas: "https://i.ibb.co/abc/Puas.jpg",
  teruja: "https://i.ibb.co/abc/Teruja.jpg"
  const wordImages_part3 = {
  // Kata kerja tambahan
  belajar: "https://i.ibb.co/abc/Belajar.jpg",
  menulis: "https://i.ibb.co/abc/Menulis.jpg",
  membaca: "https://i.ibb.co/abc/Membaca.jpg",
  mendengar: "https://i.ibb.co/abc/Mendengar.jpg",
  bercakap: "https://i.ibb.co/abc/Bercakap.jpg",
  memasak: "https://i.ibb.co/abc/Memasak.jpg",
  minum: "https://i.ibb.co/abc/Minum.jpg",
  makan: "https://i.ibb.co/abc/Makan.jpg",
  mandi: "https://i.ibb.co/abc/Mandi.jpg",
  tidur: "https://i.ibb.co/abc/Tidur.jpg",
  berjalan: "https://i.ibb.co/abc/Berjalan.jpg",
  berlari: "https://i.ibb.co/abc/Berlari.jpg",
  berenang: "https://i.ibb.co/abc/Berenang.jpg",
  memanjat: "https://i.ibb.co/abc/Memanjat.jpg",
  menyanyi: "https://i.ibb.co/abc/Menyanyi.jpg",
  menari: "https://i.ibb.co/abc/Menari.jpg",
  melukis: "https://i.ibb.co/abc/Melukis.jpg",
  menonton: "https://i.ibb.co/abc/Menonton.jpg",
  bermain: "https://i.ibb.co/abc/Bermain.jpg",
  membantu: "https://i.ibb.co/abc/Membantu.jpg",

  // Sifat tambahan
  baik: "https://i.ibb.co/abc/Baik.jpg",
  jahat: "https://i.ibb.co/abc/Jahat.jpg",
  cantik: "https://i.ibb.co/abc/Cantik.jpg",
  hodoh: "https://i.ibb.co/abc/Hodoh.jpg",
  kuat: "https://i.ibb.co/abc/Kuat.jpg",
  lemah: "https://i.ibb.co/abc/Lemah.jpg",
  bersih: "https://i.ibb.co/abc/Bersih.jpg",
  kotor: "https://i.ibb.co/abc/Kotor.jpg",
  sihat: "https://i.ibb.co/abc/Sihat.jpg",
  sakit: "https://i.ibb.co/abc/Sakit.jpg",

  // Warna tambahan
  merah_muda: "https://i.ibb.co/abc/Merah-Muda.jpg",
  biru_tua: "https://i.ibb.co/abc/Biru-Tua.jpg",
  hijau_tua: "https://i.ibb.co/abc/Hijau-Tua.jpg",
  kuning_tua: "https://i.ibb.co/abc/Kuning-Tua.jpg",
  hitam: "https://i.ibb.co/abc/Hitam.jpg",
  putih: "https://i.ibb.co/abc/Putih.jpg",
  oren: "https://i.ibb.co/abc/Oren.jpg",
  turquoise: "https://i.ibb.co/abc/Turquoise.jpg",
  navy: "https://i.ibb.co/abc/Navy.jpg",
  emas: "https://i.ibb.co/abc/Emas.jpg",

  // Nombor tambahan
  dua_puluh_satu: "https://i.ibb.co/abc/Dua-Puluh-Satu.jpg",
  dua_puluh_dua: "https://i.ibb.co/abc/Dua-Puluh-Dua.jpg",
  dua_puluh_tiga: "https://i.ibb.co/abc/Dua-Puluh-Tiga.jpg",
  dua_puluh_empat: "https://i.ibb.co/abc/Dua-Puluh-Empat.jpg",
  dua_puluh_lima: "https://i.ibb.co/abc/Dua-Puluh-Lima.jpg",
  dua_puluh_enam: "https://i.ibb.co/abc/Dua-Puluh-Enam.jpg",
  dua_puluh_tujuh: "https://i.ibb.co/abc/Dua-Puluh-Tujuh.jpg",
  dua_puluh_lapan: "https://i.ibb.co/abc/Dua-Puluh-Lapan.jpg",
  dua_puluh_sembilan: "https://i.ibb.co/abc/Dua-Puluh-Sembilan.jpg",
  tiga_puluh: "https://i.ibb.co/abc/Tiga-Puluh.jpg",

  // Tempat tambahan
  sekolah: "https://i.ibb.co/abc/Sekolah.jpg",
  universiti: "https://i.ibb.co/abc/Universiti.jpg",
  pejabat: "https://i.ibb.co/abc/Pejabat.jpg",
  bank: "https://i.ibb.co/abc/Bank.jpg",
  masjid: "https://i.ibb.co/abc/Masjid.jpg",
  gereja: "https://i.ibb.co/abc/Gereja.jpg",
  tokong: "https://i.ibb.co/abc/Tokong.jpg",
  rumah_sakit: "https://i.ibb.co/abc/Rumah-Sakit.jpg",
  pasar: "https://i.ibb.co/abc/Pasar.jpg",
  stesen_minyak: "https://i.ibb.co/abc/Stesen-Minyak.jpg",

  // Perasaan tambahan
  gembira: "https://i.ibb.co/abc/Gembira.jpg",
  sedih: "https://i.ibb.co/abc/Sedih.jpg",
  marah: "https://i.ibb.co/abc/Marah.jpg",
  takut: "https://i.ibb.co/abc/Takut.jpg",
  terkejut: "https://i.ibb.co/abc/Terkejut.jpg",
  kecewa2: "https://i.ibb.co/abc/Kecewa2.jpg",
  puas2: "https://i.ibb.co/abc/Puas2.jpg",
  lega2: "https://i.ibb.co/abc/Lega2.jpg",
  rindu2: "https://i.ibb.co/abc/Rindu2.jpg",
  cinta: "https://i.ibb.co/abc/Cinta.jpg"
  const wordImages_part4 = {
  // Kata kerja tambahan
  membeli: "https://i.ibb.co/abc/Membeli.jpg",
  menjual: "https://i.ibb.co/abc/Menjual.jpg",
  menghantar: "https://i.ibb.co/abc/Menghantar.jpg",
  menerima: "https://i.ibb.co/abc/Menerima.jpg",
  meminjam: "https://i.ibb.co/abc/Meminjam.jpg",
  mengembalikan: "https://i.ibb.co/abc/Mengembalikan.jpg",
  mencuci: "https://i.ibb.co/abc/Mencuci.jpg",
  menyapu: "https://i.ibb.co/abc/Menyapu.jpg",
  menyikat: "https://i.ibb.co/abc/Menyikat.jpg",
  memotong: "https://i.ibb.co/abc/Memotong.jpg",
  menanam: "https://i.ibb.co/abc/Menanam.jpg",
  menyiram: "https://i.ibb.co/abc/Menyiram.jpg",
  menggosok: "https://i.ibb.co/abc/Menggosok.jpg",
  menyalin: "https://i.ibb.co/abc/Menyalin.jpg",
  menekan: "https://i.ibb.co/abc/Menekan.jpg",
  menyalakan: "https://i.ibb.co/abc/Menyalakan.jpg",
  memadam: "https://i.ibb.co/abc/Memadam.jpg",
  menekan_but: "https://i.ibb.co/abc/Menekan-But.jpg",
  menahan: "https://i.ibb.co/abc/Menahan.jpg",
  mengangkat: "https://i.ibb.co/abc/Mengangkat.jpg",

  // Sifat tambahan
  panas: "https://i.ibb.co/abc/Panas.jpg",
  sejuk: "https://i.ibb.co/abc/Sejuk.jpg",
  lembut: "https://i.ibb.co/abc/Lembut.jpg",
  keras: "https://i.ibb.co/abc/Keras.jpg",
  tinggi: "https://i.ibb.co/abc/Tinggi.jpg",
  rendah: "https://i.ibb.co/abc/Rendah.jpg",
  cepat: "https://i.ibb.co/abc/Cepat.jpg",
  perlahan: "https://i.ibb.co/abc/Perlahan.jpg",
  panjang: "https://i.ibb.co/abc/Panjang.jpg",
  pendek: "https://i.ibb.co/abc/Pendek.jpg",

  // Warna tambahan
  merah_merah: "https://i.ibb.co/abc/Merah-Merah.jpg",
  biru_muda: "https://i.ibb.co/abc/Biru-Muda.jpg",
  hijau_muda: "https://i.ibb.co/abc/Hijau-Muda.jpg",
  kuning_muda: "https://i.ibb.co/abc/Kuning-Muda.jpg",
  kelabu: "https://i.ibb.co/abc/Kelabu.jpg",
  ungu: "https://i.ibb.co/abc/Ungu.jpg",
  coklat: "https://i.ibb.co/abc/Coklat.jpg",
  pink: "https://i.ibb.co/abc/Pink.jpg",
  silver: "https://i.ibb.co/abc/Silver.jpg",
  bronze: "https://i.ibb.co/abc/Bronze.jpg",

  // Nombor tambahan
  tiga_puluh_satu: "https://i.ibb.co/abc/Tiga-Puluh-Satu.jpg",
  tiga_puluh_dua: "https://i.ibb.co/abc/Tiga-Puluh-Dua.jpg",
  tiga_puluh_tiga: "https://i.ibb.co/abc/Tiga-Puluh-Tiga.jpg",
  tiga_puluh_empat: "https://i.ibb.co/abc/Tiga-Puluh-Empat.jpg",
  tiga_puluh_lima: "https://i.ibb.co/abc/Tiga-Puluh-Lima.jpg",
  tiga_puluh_enam: "https://i.ibb.co/abc/Tiga-Puluh-Enam.jpg",
  tiga_puluh_tujuh: "https://i.ibb.co/abc/Tiga-Puluh-Tujuh.jpg",
  tiga_puluh_lapan: "https://i.ibb.co/abc/Tiga-Puluh-Lapan.jpg",
  tiga_puluh_sembilan: "https://i.ibb.co/abc/Tiga-Puluh-Sembilan.jpg",
  empat_puluh: "https://i.ibb.co/abc/Empat-Puluh.jpg",

  // Tempat tambahan
  kedai: "https://i.ibb.co/abc/Kedai.jpg",
  pasaraya: "https://i.ibb.co/abc/Pasaraya.jpg",
  stesen_kereta_api: "https://i.ibb.co/abc/Stesen-Kereta-Api.jpg",
  stesen_bas: "https://i.ibb.co/abc/Stesen-Bas.jpg",
  taman: "https://i.ibb.co/abc/Taman.jpg",
  pantai: "https://i.ibb.co/abc/Pantai.jpg",
  bukit: "https://i.ibb.co/abc/Bukit.jpg",
  gunung: "https://i.ibb.co/abc/Gunung.jpg",
  sungai: "https://i.ibb.co/abc/Sungai.jpg",
  tasik: "https://i.ibb.co/abc/Tasik.jpg",

  // Perasaan tambahan
  gembira2: "https://i.ibb.co/abc/Gembira2.jpg",
  sedih2: "https://i.ibb.co/abc/Sedih2.jpg",
  marah2: "https://i.ibb.co/abc/Marah2.jpg",
  takut2: "https://i.ibb.co/abc/Takut2.jpg",
  terkejut2: "https://i.ibb.co/abc/Terkejut2.jpg",
  kecewa: "https://i.ibb.co/abc/Kecewa.jpg",
  puas: "https://i.ibb.co/abc/Puas.jpg",
  lega: "https://i.ibb.co/abc/Lega.jpg",
  rindu: "https://i.ibb.co/abc/Rindu.jpg",
  cinta2: "https://i.ibb.co/abc/Cinta2.jpg"
  const wordImages_part5 = {
  // Kata kerja tambahan
  bermain2: "https://i.ibb.co/abc/Bermain2.jpg",
  menonton: "https://i.ibb.co/abc/Menonton.jpg",
  membaca: "https://i.ibb.co/abc/Membaca.jpg",
  menulis: "https://i.ibb.co/abc/Menulis.jpg",
  melukis: "https://i.ibb.co/abc/Melukis.jpg",
  menyanyi: "https://i.ibb.co/abc/Menyanyi.jpg",
  menari: "https://i.ibb.co/abc/Menari.jpg",
  berlari: "https://i.ibb.co/abc/Berlari.jpg",
  berenang: "https://i.ibb.co/abc/Berenang.jpg",
  menaiki: "https://i.ibb.co/abc/Menaiki.jpg",

  // Sifat tambahan
  ringan: "https://i.ibb.co/abc/Ringan.jpg",
  berat: "https://i.ibb.co/abc/Berat.jpg",
  hangat: "https://i.ibb.co/abc/Hangat.jpg",
  dingin: "https://i.ibb.co/abc/Dingin.jpg",
  lebar: "https://i.ibb.co/abc/Lebar.jpg",
  sempit: "https://i.ibb.co/abc/Sempit.jpg",
  besar: "https://i.ibb.co/abc/Besar.jpg",
  kecil: "https://i.ibb.co/abc/Kecil.jpg",
  muda: "https://i.ibb.co/abc/Muda.jpg",
  tua: "https://i.ibb.co/abc/Tua.jpg",

  // Warna tambahan
  oren: "https://i.ibb.co/abc/Oren.jpg",
  navy: "https://i.ibb.co/abc/Navy.jpg",
  teal: "https://i.ibb.co/abc/Teal.jpg",
  aqua: "https://i.ibb.co/abc/Aqua.jpg",
  lime: "https://i.ibb.co/abc/Lime.jpg",
  indigo: "https://i.ibb.co/abc/Indigo.jpg",
  violet: "https://i.ibb.co/abc/Violet.jpg",
  peach: "https://i.ibb.co/abc/Peach.jpg",
  amber: "https://i.ibb.co/abc/Amber.jpg",
  navy_muda: "https://i.ibb.co/abc/Navy-Muda.jpg",

  // Nombor tambahan
  empat_puluh_satu: "https://i.ibb.co/abc/Empat-Puluh-Satu.jpg",
  empat_puluh_dua: "https://i.ibb.co/abc/Empat-Puluh-Dua.jpg",
  empat_puluh_tiga: "https://i.ibb.co/abc/Empat-Puluh-Tiga.jpg",
  empat_puluh_empat: "https://i.ibb.co/abc/Empat-Puluh-Empat.jpg",
  empat_puluh_lima: "https://i.ibb.co/abc/Empat-Puluh-Lima.jpg",
  empat_puluh_enam: "https://i.ibb.co/abc/Empat-Puluh-Enam.jpg",
  empat_puluh_tujuh: "https://i.ibb.co/abc/Empat-Puluh-Tujuh.jpg",
  empat_puluh_lapan: "https://i.ibb.co/abc/Empat-Puluh-Lapan.jpg",
  empat_puluh_sembilan: "https://i.ibb.co/abc/Empat-Puluh-Sembilan.jpg",
  lima_puluh: "https://i.ibb.co/abc/Lima-Puluh.jpg",

  // Tempat tambahan
  pejabat: "https://i.ibb.co/abc/Pejabat.jpg",
  sekolah: "https://i.ibb.co/abc/Sekolah.jpg",
  universiti: "https://i.ibb.co/abc/Universiti.jpg",
  hospital: "https://i.ibb.co/abc/Hospital.jpg",
  klinik: "https://i.ibb.co/abc/Klinik.jpg",
  restoran: "https://i.ibb.co/abc/Restoran.jpg",
  kafe: "https://i.ibb.co/abc/Kafe.jpg",
  perpustakaan: "https://i.ibb.co/abc/Perpustakaan.jpg",
  muzium: "https://i.ibb.co/abc/Muzium.jpg",
  stadium: "https://i.ibb.co/abc/Stadium.jpg",

  // Perasaan tambahan
  lega2: "https://i.ibb.co/abc/Lega2.jpg",
  gembira3: "https://i.ibb.co/abc/Gembira3.jpg",
  sedih3: "https://i.ibb.co/abc/Sedih3.jpg",
  marah3: "https://i.ibb.co/abc/Marah3.jpg",
  takut3: "https://i.ibb.co/abc/Takut3.jpg",
  terkejut3: "https://i.ibb.co/abc/Terkejut3.jpg",
  kecewa2: "https://i.ibb.co/abc/Kecewa2.jpg",
  puas2: "https://i.ibb.co/abc/Puas2.jpg",
  rindu2: "https://i.ibb.co/abc/Rindu2.jpg",
  cinta3: "https://i.ibb.co/abc/Cinta3.jpg"
  
};




