const wordImages = {
  // Kata kerja
  ambil: "https://i.ibb.co/xFDdTgC/Ambil.jpg",
  angkat: "https://i.ibb.co/CKyDRtL/Angkat.jpg",
  baca: "https://i.ibb.co/WfqmLPZ/Baca.jpg",
  bercakap: "https://i.ibb.co/K9BL7Xm/Bercakap.jpg",
  bawa: "https://i.ibb.co/CHscC4p/Bawa.jpg",
  beritahu: "https://i.ibb.co/wy13Lg4/Beritahu.jpg",
  berlari: "https://i.ibb.co/p4Y28D3/Berlari.jpg",
  bina: "https://i.ibb.co/mXcWwCN/Bina.jpg",
  bincang: "https://i.ibb.co/KWzygWy/Bincang.jpg",
  bohong: "https://i.ibb.co/2Pnfm2x/Bohong.jpg",
  cari: "https://i.ibb.co/sCs539m/Cari.jpg",
  dapat: "https://i.ibb.co/frJhvCZ/Dapat.jpg",
  curi: "https://i.ibb.co/y0s9VcZ/Curi.jpg",
  gaduh: "https://i.ibb.co/D8jpHzd/Gaduh.jpg",
  hantar: "https://i.ibb.co/zSGdVZ1/Hantar.jpg",
  hilang: "https://i.ibb.co/RhLpzbk/Hilang.jpg",
  ikut: "https://i.ibb.co/CvpSzMX/Ikut.jpg",
  jawab: "https://i.ibb.co/948pGWv/Jawab.jpg",
  jemput: "https://i.ibb.co/WDbsz0v/Jemput.jpg",
  kira: "https://i.ibb.co/8mZtG4r/Kira.jpg",
  jumpa: "https://i.ibb.co/S0g8D75/Jumpa.jpg",
  koyak: "https://i.ibb.co/s9zPC4Q/Koyak.jpg",
  langgar: "https://i.ibb.co/Gx20srh/Langgar.jpg",
  lihat: "https://i.ibb.co/2S0LmmK/Lihat.jpg",
  makan: "https://i.ibb.co/pd6WB8L/Makan.jpg",
  mandi: "https://i.ibb.co/RT8bLtZ/Mandi.jpg",
  menyanyi: "https://i.ibb.co/Z6ScJCq/Menyanyi.jpg",
  padam: "https://i.ibb.co/dW1gH8N/Padam.jpg",
  panggil: "https://i.ibb.co/28G8D2G/Panggil.jpg",
  pilih: "https://i.ibb.co/x3F0Ltv/Pilih.jpg",
  pinjam: "https://i.ibb.co/cvfh18d/Pinjam.jpg",
  rehat: "https://i.ibb.co/Z2brDNQ/Rehat.jpg",
  sebut: "https://i.ibb.co/86fbdkk/Sebut.jpg",
  simpan: "https://i.ibb.co/q9wmwmt/Simpan.jpg",
  tangkap: "https://i.ibb.co/DVg5fLD/Tangkap.jpg",
  tembak: "https://i.ibb.co/N72rk1W/Tembak.jpg",
  tempah: "https://i.ibb.co/FxrCw9R/Tempah.jpg",
  tidur: "https://i.ibb.co/Fq5Rwjf/Tidur.jpg",
  tinggal: "https://i.ibb.co/h21WTxs/Tinggal.jpg",
  tulis: "https://i.ibb.co/T2GWpqT/Tulis.jpg",
  tunggu: "https://i.ibb.co/9WnkLr3/Tunggu.jpg",

  // Sifat
  adil: "https://i.ibb.co/hVNdKzS/Adil.jpg",
  bagus: "https://i.ibb.co/hBh3wpn/Bagus.jpg",
  baik: "https://i.ibb.co/JK1Ldq6/Baik.jpg",
  besar: "https://i.ibb.co/FhF6LZD/Besar.jpg",
  kecil: "https://i.ibb.co/m9R8hNk/Kecil.jpg",
  cantik: "https://i.ibb.co/7SvN2Lf/Cantik.jpg",
  cepat: "https://i.ibb.co/QfG7V5f/Cepat.jpg",
  lambat: "https://i.ibb.co/p2t8XkH/Lambat.jpg",
  baru: "https://i.ibb.co/xyz/Baru.jpg",
  lama: "https://i.ibb.co/xyz/Lama.jpg",

  // Warna
  merah: "https://i.ibb.co/kc5R2dQ/Merah.jpg",
  biru: "https://i.ibb.co/fnJ7Z4X/Biru.jpg",
  hijau: "https://i.ibb.co/L8Xk3Z0/Hijau.jpg",
  kuning: "https://i.ibb.co/D9xR3V1/Kuning.jpg",
  hitam: "https://i.ibb.co/7kF3V9G/Hitam.jpg",
  putih: "https://i.ibb.co/pwD9YQ4/Putih.jpg",

  // Nombor
  satu: "https://i.ibb.co/1x3N2k5/Satu.jpg",
  dua: "https://i.ibb.co/2y4L5m6/Dua.jpg",
  tiga: "https://i.ibb.co/3z5N6n7/Tiga.jpg",
  empat: "https://i.ibb.co/4a7B8p9/Empat.jpg",
  lima: "https://i.ibb.co/5c9D1q2/Lima.jpg",
  enam: "https://i.ibb.co/6d1E2r3/Enam.jpg",
  tujuh: "https://i.ibb.co/7f2F3s4/Tujuh.jpg",
  lapan: "https://i.ibb.co/8g3H4t5/Lapan.jpg",
  sembilan: "https://i.ibb.co/9h4I5u6/Sembilan.jpg",
  sepuluh: "https://i.ibb.co/0i5J6v7/Sepuluh.jpg",

  // Tempat
  rumah: "https://i.ibb.co/abc/Home.jpg",
  sekolah: "https://i.ibb.co/abc/School.jpg",
  pejabat: "https://i.ibb.co/abc/Office.jpg",
  masjid: "https://i.ibb.co/abc/Mosque.jpg",
  pasar: "https://i.ibb.co/abc/Market.jpg",

  // Perasaan & lain-lain
  gembira: "https://i.ibb.co/abc/Happy.jpg",
  sedih: "https://i.ibb.co/abc/Sad.jpg",
  marah: "https://i.ibb.co/abc/Angry.jpg",
  takut: "https://i.ibb.co/abc/Scared.jpg",
  terkejut: "https://i.ibb.co/abc/Surprised.jpg",
  bosan: "https://i.ibb.co/abc/Bored.jpg",
  penat: "https://i.ibb.co/abc/Tired.jpg",
  sakit: "https://i.ibb.co/abc/Sick.jpg",
  lapar: "https://i.ibb.co/abc/Hungry.jpg",
  dahaga: "https://i.ibb.co/abc/Thirsty.jpg"
};
